### ISSUE TITLE
original error: cannot import name core （run on cpu）

### ISSUE THREAD

**Issue by NYcleaner** [hvy/chainer-visualization#1]
Hi ,,when i run  the code , an error occur  like  below:
`Traceback (most recent call last):
  File "visualize.py", line 4, in <module>
    import cupy
  File "/usr/local/lib/python2.7/dist-packages/cupy/__init__.py", line 20, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/cupy/__init__.py", line 9, in <module>
    from cupy import core  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: CuPy is not correctly installed. Please check your environment, uninstall CuPy and reinstall it with `pip install cupy --no-cache-dir -vvvv`.

original error: cannot import name core
`
I just install the cupy ,  and can't solve the problem .
please tell me  how to solve it , thanks

**Comment by hvy** [comment]
Hi,

I am not entirely sure why you get that error message. So you have CuPy installed but are trying to run it on the CPU? On the other hand, the code shouldn't really `import cupy` at the top, since this adds a GPU dependency. 

`cupy` is not used at that many locations though, and you might be able to replace those usages with `chainer.cuda.get_array_module()` and similar util functions. If I have time, I could fix this but you might as well be able to by referring to http://docs.chainer.org/en/stable/tutorial/gpu.html

**Comment by hvy** [comment]
I fixed the CuPy dependency so you should be able to run the code without having `cupy` installed.

**Comment by NYcleaner** [comment]
hey.. thank you  for your enthusiasm, but when I run the code  you have fixed, a new problem arise, I run the  code like this : 
`python visualize.py --image-filename   images/cat.jpg  --model-filename VGG_ILSVRC_16_layers.caffemodel --out-dirname results --gpu 0`

then  it report an error：
`
Traceback (most recent call last):
  File "visualize.py", line 145, in <module>
    main(args)
  File "visualize.py", line 132, in main
    serializers.load_hdf5(args.model_filename, model)
  File "/usr/local/lib/python2.7/dist-packages/chainer/serializers/hdf5.py", line 141, in load_hdf5
    with h5py.File(filename, 'r') as f:
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-4rPeHA-build/h5py/h5f.c:1930)
IOError: Unable to open file (File signature not found)
`

I just use the model  'VGG_ILSVRC_16_layers.caffemodel'  from the [link](https://gist.github.com/ksimonyan/211839e770f7b538e2d8#file-readme-md), is that the model reason？


（what's  more， the lib/model/vgg.py  have a bug,  the super() must pass on a params  like super(’ VGG, self).__init__‘）

**Comment by NYcleaner** [comment]
oh  sorry， I just get the wrong model......  the correct model is [vgg.model](https://www.dropbox.com/s/oubwxgmqzep24yq/VGG.model?dl=0), lol

**Comment by hvy** [comment]
That's correct. Did you get it to work?

**Comment by NYcleaner** [comment]
yeah， it works well，  thank  you very  much for your enthusiastic  help！

**Comment by hvy** [comment]
Great, I'll close this issue.
